### ISSUE TITLE
Elasticfence 2.3.2

### ISSUE THREAD

**Issue by parthuA1** [elasticfence/elasticsearch-http-user-auth#19]
I have ES 2.3.2 running and the existing plugin (Elasticfence 2.3.1) doesn't seem to work with it. When can I expect Elasticfence 2.3.2 to be rolled out?

**Comment by lmangani** [comment]
Latest release on 2.3.x is 2.3.3 - unfortunately the way ES plugins work right now prevent us from having cross-minor versions (unless someone has a trick I don't know)

**Comment by lmangani** [comment]
Added release for 2.3.2 
https://github.com/elasticfence/elasticsearch-http-user-auth/releases

Please re-open the ticket in case of issues/need
