### ISSUE TITLE
Empowering Non-Root Users

### ISSUE THREAD

**Issue by parthuA1** [elasticfence/elasticsearch-http-user-auth#21]
Two questions: 
a) Right now, I still see my Elasticsearch log show this:

[plugin.elasticfence      ] Invalid User: /_cluster/health 
[plugin.elasticfence      ] Invalid User: /_cluster/stats

I use root:rootpassword in Logstash, KIbana and Marvel (coz, Root is the most empowered user with no restrictions on access). I wonder why I get those Invalid User messages. 

b) Can we assign a Non-Root User the same privileges as that of a Root User?I want a non root user to be able to see marvel, kibana and everything else without any restriction. How can I accomplish this?

**Comment by lmangani** [comment]
Hi @parthuA1 
You should be able to create a new non-root user in Elasticfence and provide it with access rights to all/any resource in wildcard mode. Have you tried already? Alternatively you can whitelist your trusted servers to bypass authentication

**Comment by parthuA1** [comment]
Can you explain wildcard mode? 
The documentation of elasticfence talks about "admin" having access to "/_*" .. (This is effectively everything). But it just doesn't work. What do you think the wildcard mode should be like?

**Comment by lmangani** [comment]
This would suggest the client trying to access `/_cluster/health` is misconfigured or does not use authentication at all as the errors implies. Could you clarify where those requests are originated from?

**Comment by parthuA1** [comment]
I added "admin" as a user to Elasticfence UI. And under indices I said "/_*".  When I pull up the head plugin, I get "Forbidden Path." Despite the access being made available to /_*. 

The components attempting to connect to ES are Logstash, Marvel and Kibana. For all these three, I ensured to mention "root" and "rootpassword" in their respective config files.  

I'm just out of ideas as to a) what should be causing the problem and b) How to promote a non root user to enjoying the same privilege as a root user.  Please advise.

**Comment by lmangani** [comment]
Just in order to troubleshoot you could try adding the authentication in the URL for the offending client (ie:  http://root:rootpassword@elasticsearch.host:9200) and/or whitelisting the host for querying itself (I'll assume its not using localhost) to see if its lets connection pass.

Edit: Try whitelisting pattern "*" for the admin user and see if you get different results.

**Comment by lmangani** [comment]
```
Marvel

elasticsearch.yml:

marvel.agent.exporter.es.hosts: ["http://root:rootpassword@elasticsearch.host:9200"]
```

Did the above sort any results or new logs?

**Comment by lmangani** [comment]
The latest version accepts regex matching on the filters and should easily allow creating more powerful profiles all the way up to `/.*`. Let us know if you get a chance to try it, the README contains new examples too.
