### ISSUE TITLE
Marvel Error Due to Elasticfence

### ISSUE THREAD

**Issue by parthuA1** [elasticfence/elasticsearch-http-user-auth#22]
Two issues: 

a) Each time  I make a change in the Elasticsearch.yml file (any configuration setting), and I restart Elasticsearch and Kibana, when I attempt to log on to Marvel, I get this "Marvel: Error 400 Bad Request: No Living Connections" error. 

WHy do you think Marvel gets corrupted every time? Any template being set? 

b) I still get to see "Invalid User: /_cluster/stats"   "Invalid User: /_cluster/health" in the Elasticsearch logs file.

I infact added these two as users on the UI. But still they come up in the log file.

**Comment by parthuA1** [comment]
![marvel error](https://cloud.githubusercontent.com/assets/7647741/16280833/20736cc6-3887-11e6-8cd3-b2059bac334c.JPG)

**Comment by lmangani** [comment]
Any chance to capture the the ES requests triggering those errors? We need to understand the sequence of events to resolve this scenario

**Comment by lmangani** [comment]
The latest version accepts regex matching on the filters and should easily allow creating more powerful profiles all the way up to `/.*`. Let us know if you get a chance to try it, the README contains new examples too.
