### ISSUE TITLE
[README]web console which manages users provided in readme.md can not access.

### ISSUE THREAD

**Issue by ChristinaLy** [elasticfence/elasticsearch-http-user-auth#23]
Installed this plugin with elasticfence-2.1.1-SNAPSHOT.zip
After installation, the plugin path is $Elasticsearch_installation_path/plugins/elasticfence/

As the readme.md said, we should access the following: web console to manage users:
http://your.elasticsearch.hostname:9200/_plugin/http-user-auth-plugin/index.html
The result: Can not access.

Suggest to changed the web console:
http://your.elasticsearch.hostname:9200/_plugin/elasticfence/index.html

**Comment by lmangani** [comment]
Thanks @ChristinaLy much appreciated!
Fixed in README 2.3.x
