### ISSUE TITLE
Please - incompatible ES 2.3.5

### ISSUE THREAD

**Issue by edugfts** [elasticfence/elasticsearch-http-user-auth#26]
I'm tried installing the pugin, but....

NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Plugin [elasticfence] is incompatible with Elasticsearch [2.3.5]. Was designed for version [2.3.4]

Thanks

**Comment by lmangani** [comment]
New branch/release added, could you give it a try?

```
bin/plugin install https://raw.githubusercontent.com/elasticfence/elasticsearch-http-user-auth/2.3.5/jar/elasticfence-2.3.5-SNAPSHOT.zip
```

**Comment by edugfts** [comment]
i'm installed with success and tested...ok

Thanks a lot.

**Comment by lmangani** [comment]
Thanks for your confirmation!
