### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by akashjarad** [elasticfence/elasticsearch-http-user-auth#28]
i installed elasticsearch-http-user-auth for elasticsearch 2.3.4 . At first time every thing was working fine.
when i query my elasticsearch node through curl using query "curl localhost:9200" it asked me for user name and password and shows "Needs Basic Auth" .
when provided with password it works fine 
curl -u root:rootpasswo0d localhost:9200
returned 
{
  "name" : "Conquer Lord",
  "cluster_name" : "elasticsearch",
 .............
  },
  "tagline" : "You Know, for Search"
}

but when i query the same node through my chrome browser for first time it ask for username and password but not for second time ,or there after.

i tried restarting the elastic node but it sill does not ask for username and password.

**Comment by lmangani** [comment]
Credentials are cached by your browser likely. Try from an anonymous session and you should receive auth challenge.

**Comment by akashjarad** [comment]
no its still not working i tried ,it ask for for only first time.

**Comment by akashjarad** [comment]
![out](https://cloud.githubusercontent.com/assets/5300334/18126097/3986bf28-6f97-11e6-9ce6-051ba702b693.gif)

**Comment by lmangani** [comment]
@akashjarad this seems normal behaviour for session authentication - the anonymous browser is asking for credentials and retains them - try do the same with your google login session (or any other login) in anonymous and it should give similar results

**Comment by akashjarad** [comment]
it ask on browser restart

**Comment by akashjarad** [comment]
is there any way to reset session?

**Comment by lmangani** [comment]
@akashjarad thanks for the confirmation - this behaviour depends on the browser/settings being used rather than our Plugin

**Comment by akashjarad** [comment]
is there a way around , because i want to authenticate every request come to my elastic node , and also can i include username and password in my request header insted of url .

**Comment by lmangani** [comment]
Hi @akashjarad 
Every interaction must already be authenticated unless you white-listed your origin in ACL, as you also validated with CURL requests. You are just being confused by your browser caching behavior, while in reality you ARE using credentials on each request.
