### ISSUE TITLE
This plugin dosen't intercepte port 9300?

### ISSUE THREAD

**Issue by Guojiaju** [elasticfence/elasticsearch-http-user-auth#29]
I install the plugin ,and it's worked .But in code ,I can query datas from ES via port 9300 .So it's dosen't intercepte port 9300?

**Comment by lmangani** [comment]
Hi @Guojiaju 

9300-9400 is used by the [Transport](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-transport.html) module and is intended for asynchronous communication between nodes - definitely not for direct access. 
The scope of the plugin is user authentication instead.

Hope this helps
