### ISSUE TITLE
2.2.x ERROR: Could not find plugin descriptor

### ISSUE THREAD

**Issue by cleey** [elasticfence/elasticsearch-http-user-auth#32]
i can not install plugins in elasticsearch-2.2.0，and i have tried to install in several servers. it prompts  Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
,can you help me?

```
sudo bin/plugin install file:///usr/local/src/elasticsearch-2.2.0/elasticfence-2.2.0-SNAPSHOT.zip 
-> Installing from file:/usr/local/src/elasticsearch-2.2.0/elasticfence-2.2.0-SNAPSHOT.zip...
Trying file:/usr/local/src/elasticsearch-2.2.0/elasticfence-2.2.0-SNAPSHOT.zip ...
Downloading .DONE
Verifying file:/usr/local/src/elasticsearch-2.2.0/elasticfence-2.2.0-SNAPSHOT.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
```

**Comment by cleey** [comment]
you kan download elasticsearch 2.2.0 on:
https://www.elastic.co/downloads/past-releases/elasticsearch-2-2-0
https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.0/elasticsearch-2.2.0.tar.gz

**Comment by lmangani** [comment]
Hi @cleey 
ES 2.2.0 is already supported. If the direct install fails, try to download the archive locally before installing.
