### ISSUE TITLE
Problem while installing "EPERM: operation not permitted"

### ISSUE THREAD

**Issue by mstya** [elasticfence/elasticsearch-http-user-auth#34]
Hello!
I have a problem while installing plugin kibana-auth-plugin.
In console I got this message:

Plugin installation was unsuccessful due to error "EPERM: operation not permitted, rename 'D:\elastic_kibana\kibana-4.6.2-windows-x86\installedPlugins\.plugin.installing' -> 'D:\elastic_kibana\kibana-4.6.2-windows-x86\installedPlugins\kibana-auth-plugin'"

Have can I fix this?
Thanks!

**Comment by lmangani** [comment]
Hi @mstya I do not have a windows setup to confirm unfortunately. You can try build the plugin manually with npm and installing the locally generated package to see if this fixes the issue?

**Comment by lmangani** [comment]
Please use https://github.com/elasticfence/kibana-auth-elasticfence for native integration with Elasticfence auth, and raise the installation issue there for assistance. Thanks!
