### ISSUE TITLE
Include 2.3.1 branch

### ISSUE THREAD

**Issue by ErwanLent** [elasticfence/elasticsearch-http-user-auth#48]
Luckily I was able to find the compiled jar for 2.3.1 in the commit history.

https://github.com/elasticfence/elasticsearch-http-user-auth/blob/c7f932ba38a298b2f4f7d4fac7c36777736f1810/jar/elasticfence-2.3.1-SNAPSHOT.zip

**Comment by ryanlutgen** [comment]
2.3.1 branch now up.
