### ISSUE TITLE
Error installing 5.0.0 plugin on Windows

### ISSUE THREAD

**Issue by stevenwall** [elasticfence/elasticsearch-http-user-auth#49]
Just trying to install this plugin for the first time on Windows with this command:

`bin/elasticsearch-plugin install https://raw.githubusercontent.com/elasticfence/elasticsearch-http-user-auth/5.0.0/jar/elasticfence-5.0.0-SNAPSHOT.zip`

(I think the ReadME file has the outdated command of "plugin".  It is now "elasticsearch-plugin" on ES 5.)

I keep getting this error after it is downloaded:
`ERROR: `elasticsearch` directory is missing in the plugin zip
`

Any ideas?  I'm sure I'm doing something wrong.

Thanks,
Steve

**Comment by ryanlutgen** [comment]
This was updated for the 5.1.1 branch, but it appears to have not hit the 5.0.0 branch.  I have a PR up to remedy the situation:
https://github.com/elasticfence/elasticsearch-http-user-auth/pull/50

**Comment by stevenwall** [comment]
Thanks!  What is your remcommendation for using this plugin on other ES versions?  For example, we are currently using 5.0.2.

**Comment by ryanlutgen** [comment]
Until a 5.0.2 branch is made on this repo ( @lmangani ), you'll need to check out the code and change a few areas yourself.  You can either fork this repo via github or do the process manually.  Every 5.x version of this plugin should be compatible, so you should be able to just branch off of 5.1.1 and do this:

https://github.com/elasticfence/elasticsearch-http-user-auth/blob/5.1.1/pom.xml
https://github.com/elasticfence/elasticsearch-http-user-auth/blob/5.1.1/src/main/resources/plugin-metadata/plugin-descriptor.properties

1. Update those two files to replace "5.1.1" with "5.0.2".  See here for an example commit that updates the version: https://github.com/elasticfence/elasticsearch-http-user-auth/commit/62df5aa5f49b044f00ff54e09175368f3f90797d
2. Recompile and use the outputted zip.
3. Install the plugin as normal via the command like, either taking the .zip locally or from your repository like described in the readme.

**Comment by lmangani** [comment]
BTW @ryanlutgen you should have write rights, can you try create a branch for 5.0.2 to confirm they are in place?

**Comment by ryanlutgen** [comment]
5.0.2 Branch now up on this repo.  Should be able to install the plugin by using the command in the readme.

**Comment by ryanlutgen** [comment]
Everything should be good to go, please make another issue if there are any problems still.
