### ISSUE TITLE
Snapshot for ES 2.4.2

### ISSUE THREAD

**Issue by cks333** [elasticfence/elasticsearch-http-user-auth#57]
Hi,

I have ES 2.4.2. Is there a snapshot for ES 2.4.2 available ? I tried installing the 2.4.1 which is giving me compatibility issues.

Any help on this is appreciated.

Thanks !

**Comment by ryanlutgen** [comment]
Elasticsearch plugins need a plugin file that specifies an exact version of Elasticsearch they work on and need to be updated with every version release.  I have added a 2.4.2 copy.
