### ISSUE TITLE
Documentation on Kibana integration is misleading

### ISSUE THREAD

**Issue by quulah** [elasticfence/elasticsearch-http-user-auth#6]
The README says that you should put 'root' as the username in kibana.yml.

I ran into this: https://github.com/elasticfence/elasticsearch-http-user-auth/issues/2

> 1. Add an index filter "/.kibana" to an user which you created on Elasticfence and you set in kibana.yml

You should probably mention this or something similar in the documentation.

I created a separate admin user and added a bunch of accessable indices for it, but still had 'root' in the kibana.yml which caused:

```
[INFO ][plugin.elasticfence      ] auth failed: /_mget
```

**Comment by lmangani** [comment]
Documentation adapted with a6839a738a7bb7049ae8c19d66595c8d578688a1

Thanks!
