### ISSUE TITLE
Not able to create new user for elasticsearch using elasticsearch-http-user-auth

### ISSUE THREAD

**Issue by santhoshdevadiga** [elasticfence/elasticsearch-http-user-auth#65]
Hi
    I am not able to create a user using this plugin.  I want to create a user per index so that index will be accessible only for that particular user.

Elasticsearch v 5.1.2 
Elasticsearch-http-user-auth v5.1.2

Added configuration in elasticsearch.yml
```
elasticfence.disabled: false
elasticfence.root.password: rootpassword
```

Ran below commands to get the user list

> curl -u root:rootpassword http://localhost:9200/_httpuserauth?mode=list
[] 

For creating a user ran below commands but i got error

> curl -u root:rootpassword http://localhost:9200/_httpuserauth?mode=adduser&username=admin&password=somepass
**[1] 28647
[2] 28648
[vagrant@localhost ~]$ User already exists : null**

Please help to solve this issue.

**Comment by santhoshcd** [comment]
Ran below commands 

> curl -u root:rootpassword "http://localhost:9200/_httpuserauth?mode=adduser&username=admin&password=somepass"

instead of 

> curl -u root:rootpassword http://localhost:9200/_httpuserauth?mode=adduser&username=admin&password=somepass

**Comment by santhoshdevadiga** [comment]
Ran below commands

> curl -u root:rootpassword "http://localhost:9200/_httpuserauth?mode=adduser&username=admin&password=somepass"

instead of

> curl -u root:rootpassword http://localhost:9200/_httpuserauth?mode=adduser&username=admin&password=somepass

**Comment by lmangani** [comment]
FYI: As there is no more content hosting by elasticsearch plugins, the UI will be moved to a Kibana plugin in the future

**Comment by santhoshdevadiga** [comment]
We have a plan to use kibana but not now. 
Do you have any plan to support this plugin for Elasticsearch v5.2.2 because we are using ES v5.2.2?

To add elasticsearch-http-user-auth (v5.1.2 latest) plugin we may have to degrade the ES version from 5.2.2 to 5.1.2.
