### ISSUE TITLE
Maintaining the project

### ISSUE THREAD

**Issue by jemacom** [elasticfence/elasticsearch-http-user-auth#76]
Hi @lmangani  @ryanlutgen @TomSearch @digitalkaoz @AymanDF @kmels

I like the plugin simplicity and ease of use. While the project is currently unmaintained there still interesting for a lot of people to use. Given these points I would like to work on it and add support for current ELK versions. 

But first my knowledge about porting and supporting elasticsearch plugins is a bit limited for that reason I would like some guidance like docs to read, java classes to reimplement and so on.

Thanks all and happy hacking as usual :smile:

**Comment by lmangani** [comment]
@jemacom thanks! you're welcome to join in and maintain using the existing repository. We'll do our best to chip in whenever possible - contact me directly to arrange access rights.
