### ISSUE TITLE
How to test the user have the index permission

### ISSUE THREAD

**Issue by xlingit** [elasticfence/elasticsearch-http-user-auth#9]
I have install the plugin suscess. but when i set the user have the index permisson,how can i  to check the set successful with java API? how can i set the username and password  with java API?

![default](https://cloud.githubusercontent.com/assets/10951542/15673011/9b3553ca-2766-11e6-9da9-de8796c37f07.png)
## (remark :i have check with curl -u ... ,it is all right)

at the same time ,can give an exampe about: "Other users can access URLs under their own indices that are specified with this plugin's API."

![image](https://cloud.githubusercontent.com/assets/10951542/15673715/031d7306-276b-11e6-95a3-9d1ef558ee9d.png)

**Comment by lmangani** [comment]
The text points at the fact non-root users needs to have explicit permissions for all resources
The best way to check the validity is to perform a request to one of the intended resources.

Please re-open this ticket is useful anytime
